# Generated by Django 5.0.6 on 2024-10-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('likenum', models.BigIntegerField(blank=True, db_column='likeNum', null=True)),
                ('commentnum', models.BigIntegerField(blank=True, db_column='commentNum', null=True)),
                ('reposts_count', models.BigIntegerField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('contentlength', models.BigIntegerField(blank=True, db_column='contentLength', null=True)),
                ('create_at', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('detailurl', models.TextField(blank=True, db_column='detailUrl', null=True)),
                ('authoravatar', models.TextField(blank=True, db_column='authorAvatar', null=True)),
                ('authorname', models.TextField(blank=True, db_column='authorName', null=True)),
                ('authordetail', models.TextField(blank=True, db_column='authorDetail', null=True)),
                ('isvip', models.FloatField(blank=True, db_column='isVip', null=True)),
            ],
            options={
                'db_table': 'article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TextField(blank=True, null=True)),
                ('like_counts', models.BigIntegerField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('authorname', models.TextField(blank=True, db_column='authorName', null=True)),
                ('authorgender', models.TextField(blank=True, db_column='authorGender', null=True)),
                ('authoraddress', models.TextField(blank=True, db_column='authorAddress', null=True)),
                ('authoravatar', models.TextField(blank=True, db_column='authorAvatar', null=True)),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublicSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('judge', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'public_sentiment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WordFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(blank=True, null=True)),
                ('frequency', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'word_frequency',
            },
        ),
    ]
